--- /mnt/cs519-sp25/linux-5.15.0/mm/Makefile.orig	2025-04-13 18:09:27.087067915 -0600
+++ /mnt/cs519-sp25/linux-5.15.0/mm/Makefile	2025-04-13 16:58:17.234261678 -0600
@@ -38,7 +38,7 @@
 mmu-$(CONFIG_MMU)	:= highmem.o memory.o mincore.o \
 			   mlock.o mmap.o mmu_gather.o mprotect.o mremap.o \
 			   msync.o page_vma_mapped.o pagewalk.o \
-			   pgtable-generic.o rmap.o vmalloc.o
+			   pgtable-generic.o rmap.o vmalloc.o extent.o
 
 
 ifdef CONFIG_CROSS_MEMORY_ATTACH
